### ISSUE TITLE
nb-cli 脚手架内找不到本插件

### ISSUE THREAD

**Issue by Yizhouuu** [wlm3201/nonebot-plugin-mcpic#2]
nb-cli 脚手架内找不到本插件，无法通过 nb install 安装

**Comment by wlm3201** [comment]
![](https://pic.sl.al/gdrive/pic/2024-05-09/663c55eaaabfe.png)

**Comment by Yizhouuu** [comment]
奇怪，我这一直显示找不到包，搜索 mc 关键词也没有，请问是需要用什么手段更新源吗？
![image](https://github.com/wlm3201/nonebot-plugin-mcpic/assets/107225762/77621a61-739c-44a6-b5ee-36d3b7e3343c)

**Comment by wlm3201** [comment]
![](https://github.com/wlm3201/nonebot-plugin-mcpic/assets/77601125/6a8b8a3c-918a-4257-983d-66e732c05a06)我也不是很懂，要不进他们群问问？768887710

**Comment by Yizhouuu** [comment]
好的感谢，只要确定不是这边的问题就好🙏
